export default {
  a: [{
    name: "a",
    hiragana: "あ",
    katakana: "ア",
  }, {
    name: "i",
    hiragana: "い",
    katakana: "イ",
  }, {
    name: "u",
    hiragana: "う",
    katakana: "ウ",
  }, {
    name: "e",
    hiragana: "え",
    katakana: "エ",
  }, {
    name: "o",
    hiragana: "お",
    katakana: "オ",
  }],
  ka: [{
    name: "ka",
    hiragana: "か",
    katakana: "カ",
  }, {
    name: "ki",
    hiragana: "き",
    katakana: "キ",
  }, {
    name: "ku",
    hiragana: "く",
    katakana: "ク",
  }, {
    name: "ke",
    hiragana: "け",
    katakana: "ケ",
  }, {
    name: "ko",
    hiragana: "こ",
    katakana: "コ",
  }],
  sa: [{
    name: "sa",
    hiragana: "さ",
    katakana: "サ",
  }, {
    name: "si",
    hiragana: "し",
    katakana: "シ",
  }, {
    name: "su",
    hiragana: "す",
    katakana: "ス",
  }, {
    name: "se",
    hiragana: "せ",
    katakana: "セ",
  }, {
    name: "so",
    hiragana: "そ",
    katakana: "ソ",
  }],
  ta: [{
    name: "ta",
    hiragana: "た",
    katakana: "タ",
  }, {
    name: "ti",
    hiragana: "ち",
    katakana: "チ",
  }, {
    name: "tu",
    hiragana: "つ",
    katakana: "ツ",
  }, {
    name: "te",
    hiragana: "て",
    katakana: "テ",
  }, {
    name: "to",
    hiragana: "と",
    katakana: "ト",
  }],
  na: [{
    name: "na",
    hiragana: "な",
    katakana: "ナ",
  }, {
    name: "ni",
    hiragana: "に",
    katakana: "ニ",
  }, {
    name: "nu",
    hiragana: "ぬ",
    katakana: "ヌ",
  }, {
    name: "ne",
    hiragana: "ね",
    katakana: "ネ",
  }, {
    name: "no",
    hiragana: "の",
    katakana: "ノ",
  }],
  ha: [{
    name: "ha",
    hiragana: "は",
    katakana: "ハ",
  }, {
    name: "hi",
    hiragana: "ひ",
    katakana: "ヒ",
  }, {
    name: "hu",
    hiragana: "ふ",
    katakana: "フ",
  }, {
    name: "he",
    hiragana: "へ",
    katakana: "ヘ",
  }, {
    name: "ho",
    hiragana: "ほ",
    katakana: "ホ",
  }],
  ma: [{
    name: "ma",
    hiragana: "ま",
    katakana: "マ",
  }, {
    name: "mi",
    hiragana: "み",
    katakana: "ミ",
  }, {
    name: "mu",
    hiragana: "む",
    katakana: "ム",
  }, {
    name: "me",
    hiragana: "め",
    katakana: "メ",
  }, {
    name: "mo",
    hiragana: "も",
    katakana: "モ",
  }],
  ya: [{
    name: "ya",
    hiragana: "や",
    katakana: "ヤ",
  }, {
    name: "yu",
    hiragana: "ゆ",
    katakana: "ユ",
  }, {
    name: "yo",
    hiragana: "よ",
    katakana: "ヨ",
  }],
  ra: [{
    name: "ra",
    hiragana: "ら",
    katakana: "ラ",
  }, {
    name: "ri",
    hiragana: "り",
    katakana: "リ",
  }, {
    name: "ru",
    hiragana: "る",
    katakana: "ル",
  }, {
    name: "re",
    hiragana: "れ",
    katakana: "レ",
  }, {
    name: "ro",
    hiragana: "ろ",
    katakana: "ロ",
  }],
  wa: [{
    name: "wa",
    hiragana: "わ",
    katakana: "ワ",
  }, {
    name: "wo",
    hiragana: "を",
    katakana: "ヲ",
  }, {
    name: "n",
    hiragana: "ん",
    katakana: "ン",
  }],
}
